### ISSUE TITLE
Ошибка при запуске fmedia-0.10-linux-amd64

### ISSUE THREAD

**Issue by kmaximv** [stsaz/fmedia#1]
При запуске выдает ошибку

```
$ fmedia --gui
/usr/local/bin/fmedia: 1: /usr/local/bin/fmedia: realpath: not found
dirname: пропущен операнд
По команде «dirname --help» можно получить дополнительную информацию.
/usr/local/bin/fmedia: 7: /usr/local/bin/fmedia: /fmedia-bin: not found
```

**Comment by stsaz** [comment]
Похоже, что realpath не установлен.  На Fedora он входит в состав пакета coreutils.  Какая у вас ОС?

Попробуйте запустить напрямую fmedia-bin:

env LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/fmedia-0 /usr/local/fmedia-0/fmedia-bin

P.S. Аргумент --gui не работает для Linux, графический интерфейс сделан пока только для Windows.
