### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by ElectronWrestler** [stsaz/fmedia#100]
I want to create a log of files played.
In Windows 10 batch file the line: fmedia --random myplaylist.m3u8>>LogFile.txt
displays fmedia --random myplaylist.m3u8 1>>LogFile.txt on the console but does not create the file.

The same command line in the console will create the file, but does not write to it.
Is this a fmedia issue or something I don't understand about windows?
Thanks

**Comment by stsaz** [comment]
Hi!
fmedia TUI uses stderr stream for displaying because stdout is often used for passing audio data to other applications.

You should use this command:
```
fmedia --random myplaylist.m3u8 2>>LogFile.txt
```

FYI:
https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)
