### ISSUE TITLE
support .ts format

### ISSUE THREAD

**Issue by NurjanovUlugbek** [stsaz/fmedia#12]
Добрый день.
Хотел сказать спасибо за плеер.. Хотел спросить
1) Как использовать через прокси ваш плеер?
2) Как прописать юзер агент чтобы слушать онлайн радио?
можете проверить эту ссылку радио вещает aac+ формате aacplus
Пример с сайта fmplay.ru
http://109.239.129.43:8000/eldoradio-48.aac я не смог на вашем плеер проиграть эту ссылку..

AIMP читает этот формат там надо прописать юзерагент FMPLAYRU оно читает без проблем..

Было бы здорово если ваш плеер тоже поддерживал этот формат и прокси а юзерагент я несмог настроит

Заранее благодарен

**Comment by stsaz** [comment]
Здравствуйте!

1. Сейчас нет такой возможности - он умеет только напрямую.  Я постараюсь добавить поддержку прокси (HTTP) в следующих версиях.

2. AAC формат (LC, HE, HEv2) поддерживается для радио трансляций.  В том радио, ссылку которого вы привели, проблема немного в другом - fmedia не понимает content type `audio/aac` (он понимает только `audio/aacp`).  В следующей версии это будет исправлено.
User agent - да, прописать нельзя сейчас.  Это я могу добавить, но действительно ли это нужно?  У меня ваша ссылка с исправлением content type играется нормально, т.е. user agent на это влиять не должен (разве что сервер другой content type высылает для плеера FMPLAYRU ?).

Спасибо за отзыв!

**Comment by NurjanovUlugbek** [comment]
Спасибо ждем тогда

**Comment by stsaz** [comment]
Выпустил версию v1.4 - там добавлена возможность работы через прокси:
В fmedia.conf файле настройка выглядит так:
```# proxy "127.0.0.1:8080"```
Удалите `#` и исправьте её на ```proxy "ВАШ_ПРОКСИ:ВАШ_ПОРТ"```
Сейчас поддерживается только HTTP прокси, SOCKS - нет.

Также добавил поддержку `audio/aac`!

**Comment by NurjanovUlugbek** [comment]
Круто спасибо за ваш плеер и прокси.
Этот формат тоже добавьте  пожалуйста в следующий билд я не смог воспроизвести 
http://hls-01-dorognoe-nostalgia.emgsound.ru/19/64/playlist.m3u8
Заранее благодарен..

ПС че понравился мне в вашем плеере то что звучит на подобия APOLLO

**Comment by stsaz** [comment]
У этого радио формат чуть сложнее, тут потребуется время, но постепенно буду двигаться в эту сторону.  Тогда пока этот issue закрывать не буду.  Итого нужно добавить:
* support HLS
* support .ts format

**Comment by NurjanovUlugbek** [comment]
Спасибо ждем тогда..  Как вашем плеер настроить что бы он поддерживал юникод
![default](https://user-images.githubusercontent.com/4905501/51098592-38d9da00-17ed-11e9-9f5f-de590419c10a.png)   title  на русском не отображается

**Comment by stsaz** [comment]
Там сейчас поддерживается только кодировка win1252 (latin), и UTF-8 он, получается, не видит.  Я исправлю это, спасибо что подсказали!

**Comment by NurjanovUlugbek** [comment]
добрый вечер 
Не читает HLS как возпроизвести?

**Comment by NurjanovUlugbek** [comment]
[info] net.hls: *6:	resolving host hls-01-radio7-alone.emgsound.ru...
12:19:49.783 :1fa4 [info] net.hls: *6:	connecting to hls-01-radio7-alone.emgsound.ru (91.108.34.3:80)...
12:19:49.784 :1fa4 [warning] net.hls: *6:	I/O timeout
12:19:49.787 :1fa4 [info] net.hls: *6:	resolving host hls-01-radio7-alone.emgsound.ru...
12:19:49.797 :1fa4 [info] net.hls: *6:	connecting to hls-01-radio7-alone.emgsound.ru (91.108.34.3:80)...
12:19:49.961 :1fa4 [error] core: unknown file format: ts
12:19:49.964 :1fa4 [error] core: module not found: ts
12:19:49.967 :1fa4 [error] net.hls: *6:	no module configured to open .ts stream

**Comment by stsaz** [comment]
> no module configured to open .ts stream
Этот формат не поддерживается сейчас. Возможно, что в будущих релизах будет реализовано, но когда именно - не могу сказать.

**Comment by stsaz** [comment]
it's in TODO list
