### ISSUE TITLE
Несколько моментов по оформлению

### ISSUE THREAD

**Issue by RJ2k6** [stsaz/fmedia#13]
1. При выходе не сохраняются настройки выбора темы и ширина колонок. После рестарта эти параметры становятся по-умолчанию. Выбор темы пофиксил, вручную отредактировав fmedia.conf - поставил 1 вместо 0 рядом с параметром theme в разделе # Set theme index on startup. Параметры ширины колонок не нашел.
2. При выборе темы Dark цвет курсора в плэйлисте почти совпадал с цветом текста названия трека, из-за чего текст под курсором был невиден. Пофиксил, отредактировав параметры цветов фона и шрифта в theme.conf. Но пришлось ставить вынужденный цвет текста, а не тот, который хотелось бы. Было бы неплохо добавить и редактирование цвета курсора.
<a href="https://fastpic.ru/view/106/2018/1221/ea02eec0438727759b43e85a2ef91559.png.html" target="_blank"><img src="https://i106.fastpic.ru/thumb/2018/1221/59/ea02eec0438727759b43e85a2ef91559.jpeg" border="0"></a>
Это всё было под Windows 7 x64.

**Comment by stsaz** [comment]
1. Да, есть такая проблема, вообще мало что сохраняется автоматически сейчас - разве что параметры окон и плейлисты.  Постараюсь сделать и остальные настройки таким же образом.  Кстати, ширину колонок сейчас можно отредактировать в fmedia.gui файле.

2. Цвет курсора добавлю, да.  Сейчас там используется стандартная Explorer тема для списка - `style explorer_theme`.  Наверное тогда я её уберу для тёмной темы и поставлю свой цвет для выделений.  Вы пока для эксперимента тоже можете в themes.conf для тёмной темы убрать слово `explorer_theme` из списка стилей.

Спасибо за отзыв!

**Comment by stsaz** [comment]
В версии v1.4 выбранная тема теперь сохраняется!  Ещё предстоит сделать:
* Авто-сохранение ширины колонок плейлиста
* Выбор цвета фона выделенных строк в плейлисте

**Comment by stsaz** [comment]
> Авто-сохранение ширины колонок плейлиста

сделано

**Comment by RJ2k6** [comment]
Наконец-то) Спасибо!

**Comment by stsaz** [comment]
added to TODO list
