### ISSUE TITLE
support CMakeList?

### ISSUE THREAD

**Issue by CS2Us** [stsaz/fmedia#14]
hi, stsaz, could you make the project support CMakeList?

**Comment by stsaz** [comment]
Hello!
Currently I don't use cmake to build fmedia (the official binaries are built with pure `make`).
But if someone adds cmake support, I can merge it into master branch!
The problem with this though is that it may become obsolete with each new release as I don't want to take the burden of updating it.  In that case someone may need to update it periodically.
