### ISSUE TITLE
Исчезает плейлист

### ISSUE THREAD

**Issue by RJ2k6** [stsaz/fmedia#20]
Заметил один неприятный баг. Настругал штук сорок композиций в плейлист. И постоянно его слушаю. И очень часто этот плейлист исчезает. Я даже не знаю, при каких именно обстоятельствах он исчезает. Вот раз... открываешь плеер, а там, в плейлисте, пусто. Благо, что я сохраняю плейлист и вставляю его в пустое поле. Система Win 7 x64.

**Comment by stsaz** [comment]
В следующий раз когда заметите что плейлист пустой - попробуйте открыть в блокноте файл `c:\Users\ВАШЕ_ИМЯ\AppData\Roaming\fmedia\list1.m3u8`.  В этот файл при закрытии программы записываются трэки, а при запуске программы оттуда вычиываются.  Скорее всего программа закрылась с ошибкой и не успела записать плейлист файл.
Скажите, а перед тем как плейлист пустой при запуске - вы открывали и закрывали несколько вкладок?  Конвертировали аудио файлы?  Или просто был один плейлист и ничего такого?

**Comment by RJ2k6** [comment]
> Скорее всего программа закрылась с ошибкой и не успела записать плейлист файл.
Ааа. Ну, теперь понятно. Слушал музыку перед сном. И часто засыпал. А комп по таймеру сам выключался, закрыв принудительно все запущенные программы. Странно, что плейлист перезаписывается даже тогда, когда в него не было внесено изменений.

**Comment by stsaz** [comment]
> плейлист перезаписывается даже тогда, когда в него не было внесено изменений.

Я постараюсь подумать, что можно сделать по этому поводу.  Как минимум нужно сделать, чтобы плейлисты не портились (не очищались).

**Comment by RJ2k6** [comment]
И что характерно, у меня висит еще один плейлист в другом ярлыке (файл list2.m3u8), в котором я часто меняю композиции (в первом плейлисте не меняю). Так вот он не очищается, в отличие от первого плейлиста. Вот такое наблюдение.

**Comment by stsaz** [comment]
В v1.11 сделана атомарная запись в файл, т.е. теперь портиться плейлисты не должны.
