### ISSUE TITLE
Digital Output Yamaha Mixer MG16XU

### ISSUE THREAD

**Issue by anes3003** [stsaz/fmedia#22]
Hello Stsaz,

I have tested fmedia in our Church computer, it is working well with analog output, but didn't work with digital usb output from Yamaha Mixer MG16XU, can not capture the sound.

At the moment, we are using Reaper to do sermon recording, but we'd love if we could do it using fmedia, which is very light but same target result.

Could you please kindly help to add capability to record from Yamaha Mixer MG series?

Thank you in advance.

**Comment by stsaz** [comment]
Hello!
Please try v1.11.
Maybe the issue is because of 5.1 or 7.1 soundcard, which fmedia didn't support until now.
