### ISSUE TITLE
Fmedia v1.3 won't split large .flac files when there's an apostrophe in the path

### ISSUE THREAD

**Issue by marcerickson** [stsaz/fmedia#23]
Apostrophe in folder name or/and file name makes split command hang. Path was enclosed in single quotes.  
Example:
marc@PET310S:~$ sudo /usr/local/fmedia-1/fmedia '/data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles' Second Album/The Beatles - The Beatles' Second Album (UICY-76430).cue' --cue-gaps=0 --out='/data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles' Second Album/$tracknumber $artist - $title.flac'
> 

Renamed to remove apostrophe from folder name:
marc@PET310S:~$ sudo /usr/local/fmedia-1/fmedia '/data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles' Second Album (UICY-76430).cue' --cue-gaps=0 --out='/data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/$tracknumber $artist - $title.flac'
bash: syntax error near unexpected token `('

Renamed to remove apostrophe from folder name and .cue and .flac file names:
marc@PET310S:~$ sudo /usr/local/fmedia-1/fmedia '/data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).cue' --cue-gaps=0 --out='/data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/$tracknumber $artist - $title.flac'
[sudo] password for marc: 
fmedia v1.3 (linux-amd64)

#1 "The Beatles - Can't Buy Me Love " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:17.800 (6,076,980 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:17 / 2:17
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/01 The Beatles - Can't Buy Me Love.flac, 9006 kbytes

#2 "The Beatles - Do You Want To Know A Secret " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:01.226 (5,346,096 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:01 / 2:01
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/02 The Beatles - Do You Want To Know A Secret.flac, 6246 kbytes

#3 "The Beatles - Thank You Girl " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:03.720 (5,456,052 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:03 / 2:03
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/03 The Beatles - Thank You Girl.flac, 7475 kbytes

#4 "The Beatles - A Taste Of Honey " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:06.360 (5,572,476 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:06 / 2:06
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/04 The Beatles - A Taste Of Honey.flac, 6326 kbytes

#5 "The Beatles - It Won't Be Long " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:14.906 (5,949,384 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:14 / 2:14
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/05 The Beatles - It Won't Be Long.flac, 8695 kbytes

#6 "The Beatles - I Wanna Be Your Man " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:00.533 (5,315,520 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:00 / 2:00
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/06 The Beatles - I Wanna Be Your Man.flac, 7721 kbytes

#7 "The Beatles - There's A Place " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 1:54.040 (5,029,164 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 1:54 / 1:54
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/07 The Beatles - There's A Plac.flac, 6275 kbytes

#8 "The Beatles - Roll Over Beethoven " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:49.120 (7,458,192 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:49 / 2:49
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/08 The Beatles - Roll Over Beethoven�.flac, 10852 kbytes

#9 "The Beatles - Misery " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 1:52.720 (4,970,952 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 1:52 / 1:52
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/09 The Beatles - Misery.flac, 6402 kbytes

#10 "The Beatles - Boys " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:29.400 (6,588,540 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:29 / 2:29
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/10 The Beatles - Boys.flac, 8325 kbytes

#11 "The Beatles - Devil In Her Heart " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:29.946 (6,612,648 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:29 / 2:29
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/11 The Beatles - Devil In Her Heart).flac, 9757 kbytes

#12 "The Beatles - Not A Second Time " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:12.360 (5,837,076 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:12 / 2:12
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/12 The Beatles - Not A Second Time.flac, 8443 kbytes

#13 "The Beatles - Money " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:46.973 (7,363,524 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:46 / 2:46
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/13 The Beatles - Money.flac, 10778 kbytes

#14 "The Beatles - Till There Was You " /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).flac 110.61 MB, 2:21.293 (6,231,036 samples), 488 kbps, FLAC, 44100 Hz, int16, stereo

[=====================================================================.] 2:21 / 2:21
saved file /data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/14 The Beatles - Till There Was You.flac, 7157 kbytes
marc@PET310S:~$

**Comment by stsaz** [comment]
In bash you can't use a single quote *inside* single-quoted string - you should escape it (`'a'\''b'`) or put it inside double-quoted string (`"a'b"`).
