### ISSUE TITLE
Space in names in .cue file contents causes odd behaviour

### ISSUE THREAD

**Issue by marcerickson** [stsaz/fmedia#24]
If files are renamed, they play normally.

Command:
marc@PET310S:~$ sudo /usr/local/fmedia-1/fmedia '/data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/The Beatles - The Beatles Second Album (UICY-76430).cue' --cue-gaps=0 --out='/data4/The Beatles (split single file) backup/4 Box Sets/2014 Meet The Beatles! - Japan Box/02 The Beatles Second Album/$tracknumber $artist - $title.flac'

Flies produced (all files in directory listed):
.
├── [    9222645]  01 The Beatles - Can't Buy Me Love
├── [    6396727]  02 The Beatles - Do You Want To Know A Secret\177.flac
├── [    7655226]  03 The Beatles - Thank You Girl
├── [    6477906]  04 The Beatles - A Taste Of Honey\001.flac
├── [    8904241]  05 The Beatles - It Won't Be Long\002.flac
├── [    7906696]  06 The Beatles - I Wanna Be Your Man
├── [    6426261]  07 The Beatles - There's A Place\010.flac
├── [   11113128]  08 The Beatles - Roll Over Beethoven\12423442515\11416641475\10422257503\11125047105\10120644506\11623644524䌽
├── [    6556186]  09 The Beatles - Misery
├── [    8525433]  10 The Beatles - Boys
├── [    9991433]  11 The Beatles - Devil In Her Heart).flac
├── [    8646589]  12 The Beatles - Not A Second Time\002.flac
├── [   11037221]  13 The Beatles - Money
├── [    7329459]  14 The Beatles - Till There Was You
├── [    1642821]  booklet01.jpg
├── [    1705512]  booklet02.jpg
├── [     899139]  CD.jpg
├── [    3389623]  front.jpg
├── [          0]  list.txt
├── [     275190]  obi.jpg
├── [    1607585]  rear.jpg
├── [       1633]  The Beatles - The Beatles Second Album (UICY-76430).cue
├── [  115983517]  The Beatles - The Beatles Second Album (UICY-76430).flac
└── [        400]  Tracks.txt

   241694597 bytes used in 0 directories, 24 files

Cue file contents:
REM GENRE Rock
REM DATE 2014
REM DISCID AD076C0E
REM COMMENT "ExactAudioCopy v1.0b3"
PERFORMER "The Beatles"
TITLE "The Beatles Second Album (UICY-76430)"
FILE "The Beatles - The Beatles Second Album (UICY-76430).flac" WAVE
  TRACK 01 AUDIO
    TITLE "Can't Buy Me Love "
    PERFORMER "The Beatles"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Do You Want To Know A Secret "
    PERFORMER "The Beatles"
    INDEX 01 02:17:60
  TRACK 03 AUDIO
    TITLE "Thank You Girl "
    PERFORMER "The Beatles"
    INDEX 01 04:19:02
  TRACK 04 AUDIO
    TITLE "A Taste Of Honey "
    PERFORMER "The Beatles"
    INDEX 01 06:22:56
  TRACK 05 AUDIO
    TITLE "It Won't Be Long "
    PERFORMER "The Beatles"
    INDEX 01 08:29:08
  TRACK 06 AUDIO
    TITLE "I Wanna Be Your Man "
    PERFORMER "The Beatles"
    INDEX 01 10:44:01
  TRACK 07 AUDIO
    TITLE "There's A Place "
    PERFORMER "The Beatles"
    INDEX 01 12:44:41
  TRACK 08 AUDIO
    TITLE "Roll Over Beethoven "
    PERFORMER "The Beatles"
    INDEX 01 14:38:44
  TRACK 09 AUDIO
    TITLE "Misery "
    PERFORMER "The Beatles"
    INDEX 01 17:27:53
  TRACK 10 AUDIO
    TITLE "Boys "
    PERFORMER "The Beatles"
    INDEX 01 19:20:32
  TRACK 11 AUDIO
    TITLE "Devil In Her Heart "
    PERFORMER "The Beatles"
    INDEX 01 21:49:62
  TRACK 12 AUDIO
    TITLE "Not A Second Time "
    PERFORMER "The Beatles"
    INDEX 01 24:19:58
  TRACK 13 AUDIO
    TITLE "Money "
    PERFORMER "The Beatles"
    INDEX 01 26:32:10
  TRACK 14 AUDIO
    TITLE "Till There Was You "
    PERFORMER "The Beatles"
    INDEX 01 29:19:08

**Comment by stsaz** [comment]
It's already fixed:
```
fmedia v1.4 - Jan 7, 2019
...
 - file.out: Invalid characters in filename when using auto-naming (v0.22 bug)
   If the value of $-variable ends with a space, then it might result in
    corrupted output filename.
```
