### ISSUE TITLE
No hotkey for Mouse Whell for Vol Up/Down

### ISSUE THREAD

**Issue by GiacomoBianchi** [stsaz/fmedia#28]
First of all I would like to congrats with you for this amazing program.
I spent a lot of time to find the hotkeys table to set Mouse Whell as Vol Up/down command, but no way. I know this is not an issue, but it is the only way I could tell you, if there was a discord channel I used that.
Thanks man!

**Comment by stsaz** [comment]
Hi!
Currently you can control the volume with mouse wheel only while the mouse cursor is on volume scroll bar.  It works on both Windows and Linux.
I'm not sure if I'll be able to add a feature for modifying this behaviour by any fmedia configuration.
