### ISSUE TITLE
Is -i supposed to write to the errorStream?

### ISSUE THREAD

**Issue by SimonCoFox** [stsaz/fmedia#29]
Hi there, 

recently started to use fmedia and was trying to read out the output of `-i `via the outputStream but only received empty strings... Eventually got the output by reading the errorStream. Is there a particular reason that `-i `sends data over the errorStream or would it be possible to output the data via the outputSteam?

Code that worked for me:
`val process = startFmedia(source.absolutePath, "-i")`
` process.waitFor()`
 `val infos = process.errorStream.bufferedReader().readText().split(", ")`

Best Regards,
Simon

**Comment by stsaz** [comment]
`-i` writes to stderr because fmedia outputs debug logs to stdout and it's convenient this way.
