### ISSUE TITLE
I have a CHIP - armv7l.  Any hope of a compiled version?

### ISSUE THREAD

**Issue by salamanders** [stsaz/fmedia#3]
Not sure if all the dependencies would make it difficult, but it would be nice to have for my CHIP!  I believe the raspberry pi is similar.

**Comment by stsaz** [comment]
Support for ARM would be great, but at this time I have no configured build environment for ARM. Currently we can only hope if someone will contribute patches or at least guidance on how to do that.

**Comment by stsaz** [comment]
added to TODO list
