### ISSUE TITLE
Using --channels results in high pitched jittering recording

### ISSUE THREAD

**Issue by SimonCoFox** [stsaz/fmedia#30]
Hi again,

when recording I was trying to use the `--channels:mono` command, unfortunately resulting in a jittery and high pitched recording. 
Code that works fine:
`
val process = startFmedia(
                    "--record",
                    "--dev-capture=${index}",
                    "--out=${sink.absolutePath}",
                    "--overwrite",
                    "--mpeg-quality=256"
            )
`

As soon as I use --channels though (all 3 options have the same problem) the sound becomes weird.
`
val process = startFmedia(
                    "--record",
                    "--dev-capture=${index}",
                    "--out=${sink.absolutePath}",
                    "--overwrite",
                    "--mpeg-quality=256",
                    "--channels=mono"
            )
`

Maybe I don´t understand how to use it properly, any help would be appreciated. 

Best Regards,
Simon

**Comment by stsaz** [comment]
Try to record with `--channels=mono` into .wav, not into .mp3 - does it work?
