### ISSUE TITLE
Peaks in sound file after combining two .wav files

### ISSUE THREAD

**Issue by SimonCoFox** [stsaz/fmedia#31]
Hi again, 

I was trying to use fmedia to attach one .wav file to another .wav file but when playing back the merged file I get a nasty short screech at the point where the first file ends and the new one begins. My assumption is that it´s the wav header that causes this behaviour but I am not sure how to effectively cut out the header. 
I am currently feeding the 2 .wav files into the stdin as byte arrays and generate the new wav file with `--out`. Apart from the short screech its working fine. 

Is there a more elegant way to use fmedia to attach one wav file to another that I am missing or do I have to figure out how to remove the header (if that is the problem here) 

Code Snippet:
fun merge(sourceA: Snippet, sourceB: Snippet, sink: File): CompletableFuture<Snippet> {

        if (sourceA.isEmpty()) return CompletableFuture.completedFuture(sourceB)
        if (sourceB.isEmpty()) return CompletableFuture.completedFuture(sourceA)

        return CompletableFuture<Snippet>().also { done ->
            thread {
                val encoder = startFmedia("@stdin.wav", "--out=${sink.absolutePath}", "--overwrite")
                encoder.outputStream.use { output ->
                    fun feedFile(file: File) {
                        val decoder = startFmedia(file.absolutePath, "--out=@stdout.wav", "--notui")
                        decoder.inputStream.use { inputStream ->
                            val fedBytes = inputStream.copyTo(output)
                            output.flush()
                            Log.info("fed $fedBytes bytes to fmedia")
                        }
                    }

                    feedFile(sourceA.file)
                    feedFile(sourceB.file)
                }
                encoder.waitFor()
                done.complete(Snippet.parse(sink))
            }
        }
    }

Any suggestions would be appreciated. 

Best Regards,
Simon

**Comment by stsaz** [comment]
fmedia can't contatenate several files into one - it's in TODO list:

> join several files into one
