### ISSUE TITLE
JACK audio support?

### ISSUE THREAD

**Issue by mxmilkb** [stsaz/fmedia#34]
Support for [JACK](https://jackaudio.org/) audio ports would be amazing.

**Comment by stsaz** [comment]
I think it's a good idea!  I will look at the code samples to estimate how much time it can take.

**Comment by stsaz** [comment]
v1.15 supports recording from JACK

**Comment by mxmilkb** [comment]
I'm trying this out at the moment, is capture available in the GUI yet?

**Comment by stsaz** [comment]
fmedia GUI on Linux is very simple, it doesn't support recording yet.
I hope I'll add it in the future.
