### ISSUE TITLE
Voice-Activated Recording?

### ISSUE THREAD

**Issue by johnyradio** [stsaz/fmedia#36]
Does fast media recorder support Voice-Activated Recording?
thx

**Comment by stsaz** [comment]
Yes.  Take a look at this argument:

```
--start-dblevel=DB Skip initial audio until input signal level goes above DB (-100dB..0dB)
```

If you use it, fmedia will start to write to a file only after a loud signal is received.  But you have to set a proper signal level.  If you set it too low or too high - it may not work as expected.

**Comment by johnyradio** [comment]
Thx! I'll try it.
