### ISSUE TITLE
Notification icon for recording?

### ISSUE THREAD

**Issue by hced** [stsaz/fmedia#39]
Hi, I'm not sure if you're willing to implement an option to show a simple icon (eg. mic) when recording audio with fmedia? That would be very handy.

If not, I'm trying to figure out how to code the simplest solution for this as ever possible: just an app that shows an icon when active, and when quit, the icon disappears. Shouldn't be too difficult, I guess. Problem is I know nothing about desktop development for Windows. Do you have any suggestion where to start? (I've downloaded latest Visual Studio.)

**Comment by stsaz** [comment]
> simple icon (eg. mic) when recording audio
A tray icon is already shown while recording from fmedia GUI (Ctrl+R).

Do you want this feature when executing fmedia from console?

**Comment by hced** [comment]
> > simple icon (eg. mic) when recording audio
> 
> Do you want this feature when executing fmedia from console?

Oh, didn't know it had an icon (never used the GUI yet.) But yes, if that's ok with you, it would be great having a flag for showing the recording icon when used from console. (My main usage of fmedia is to triggered it via Autohotkey and buttons in Directory Opus.)

**Comment by stsaz** [comment]
added to TODO list
