### ISSUE TITLE
Long, high sample rate recording crashing after ~1h35min

### ISSUE THREAD

**Issue by luciano-censoni** [stsaz/fmedia#41]
Hi!

I'm using fmedia to programatically record from an ultrasound microphone for long periods at a time, and twice in a row the program crashed and deleted the output file after ~1h35min. Slightly shorter recordings (like 1h29min) saved properly without any issue.

I'm recording in .wav format, 384 kHz sampling rate, 16 bit, mono.

Please find attached the output of the --debug option from around the time of the crash to the end of the output. Could it be some kind of integer or long overflow? I'm particularly suspicious of the file write offset position since it seems to crash when the offset becomes larger than +2147483647 (INT_MAX).

Thank you!
Luciano
[error-debug.txt](https://github.com/stsaz/fmedia/files/4307917/error-debug.txt)

**Comment by stsaz** [comment]
Hello!
.wav format has a limit of 4gb (2 billion samples * 2 bytes per sample in your case) data per chunk - it's just not possible to store it in .wav format!
Consider using .flac instead, but it may not support such a huge sampling rate value.

**Comment by luciano-censoni** [comment]
Thanks for the response!

As it turns out, 384 kHz is exactly the upper limit for .flac, so changing the format allowed me to complete long recordings successfully. I'm marking the issue "closed".
