### ISSUE TITLE
Make record buffer adjustable from the command line

### ISSUE THREAD

**Issue by EPNW** [stsaz/fmedia#44]
It seems to me that, when recording using fmedia, the recorded data is written to the output file or stream once an internal buffer of 2^16 bytes is full. It would be nice if one is able to speficy this buffer size from the command line.

Using [arecord](https://linux.die.net/man/1/arecord) one can specify a buffer time or a buffer size.

**Comment by stsaz** [comment]
There are 2 buffers in fmedia when recording audio to a file:
1. ALSA input buffer in milliseconds:
```mod_conf "alsa.in" {
	buffer_length 500
```

2. Output file buffer in bytes:
```mod_conf "#file.out" {
	buffer_size 64k
```

You can change them in fmedia.conf

**Comment by EPNW** [comment]
Hi,
Thanks for the answer!
Is there any option to set this from the comand line? The buffer size I want to use depends on my application which calls fmedia and processes its std output stream. Changing the conf every time would be possible, but a bit inconvenient.

Side question: What if I'm not using ALSA, since I'm on Windows?

**Comment by stsaz** [comment]
> Is there any option to set this from the comand line

Not at the moment, but it should be easy to add this argument.

> since I'm on Windows?

It's the same:

```
mod_conf "wasapi.in" {
...
	# in msec
	buffer_length 100
```

**Comment by EPNW** [comment]
Thank you,
this works :)

But it would still be nice to set this from the comand line. I've updated this issues title and leave it open.

**Comment by stsaz** [comment]
v1.17:
