### ISSUE TITLE
Request:  playback speed , loop

### ISSUE THREAD

**Issue by superuser7777** [stsaz/fmedia#45]
*Change the playback speed.
*Loop playback (track, playlist)

-----
I'm a great fan of FMEDIA!

**Comment by superuser7777** [comment]
This is an amateur's idea. Would it be easier to implement it here?
  * Winamp DSP Plugin
  * VST Plugin

**Comment by stsaz** [comment]
> *Change the playback speed.
> *Loop playback (track, playlist)

Do you want these features in GUI version or the command line version?
Can you suggest an example on how you would like it to be?


> This is an amateur's idea. Would it be easier to implement it here?
>     Winamp DSP Plugin
>     VST Plugin

Support for these types of plugins in fmedia would be great, but I guess it requires much time to implement this.

**Comment by stsaz** [comment]
added to TODO list
