### ISSUE TITLE
How to use Core.dll directly?

### ISSUE THREAD

**Issue by mskee57** [stsaz/fmedia#47]
Hi,
I want to use Core.dll directly via Delphi and I expected to see a group of functions available from the dll, but I see only 

core_free
core_init

I am opening an "issue" here as a last resort........

I tried in vain to find an example of any usage via any language using Google,.....can someone point me to at least a basic tutorial?

Thanks,
Mark

**Comment by stsaz** [comment]
Hello!
Please use `src/main.c` as an example on how to use fmedia core.  This is what `fmedia.exe` binary does.
`core_init` function returns the interface which is described in `src/fmedia.h` file.  Note that you need to convert some code from `src/fmedia.h` to Pascal.

Consider sending a pull request here when you'll have a working example in Pascal!
