### ISSUE TITLE
How do I specify specific audio device (capture) from commandline?

### ISSUE THREAD

**Issue by hced** [stsaz/fmedia#50]
Since you can specify audio device (capture) in the GUI app, I assume it's also possible in the commandline version, right?

Here's what I got so far (does this use the 'default' sound device?) :
`fmedia --record -o rec.wav --format=int16 --channels=stereo --rate=44100`

If possible, how do I include a specific audio device in this command? Mine's called "SPDIF (RME HDSPe AIO)". The documentation didn't describe this, or maybe I'm blind.

**Comment by stsaz** [comment]
You need to use `--dev-capture=NUMBER` as described here:
https://stsaz.github.io/fmedia/recording/#device
