### ISSUE TITLE
Request: --globcmd=pause|resume

### ISSUE THREAD

**Issue by hced** [stsaz/fmedia#52]
I hope I'm not mistaken, but this is currently not possible, right? If not, I'd find it really useful (I use fmedia to sample my system, toggling it on/off via AutoHotkey and instead of recording multiple files, I'd rather have the option for pausing current rec).

**Comment by stsaz** [comment]
Yes, it would be useful.  Just note that in paused state the recording will continue, but the data will be just thrown off until you resume.

**Comment by hced** [comment]
> the data will be just thrown off until you resume.

I’d be more than happy for that!

**Comment by stsaz** [comment]
v1.20:

` + new --globcmd commands: next, pause, unpause`
