### ISSUE TITLE
Recording is destroyed if stop when paused

### ISSUE THREAD

**Issue by hced** [stsaz/fmedia#53]
If you `--globcmd=pause` and then `--globcmd=stop`, the recording gets destroyed.

Steps to reproduce:

1. `C:\Portable\fmedia\fmedia.exe --record -o D:\Capture\REC\audiofile.wav --dev-loopback=0 --format=int16 --channels=stereo --rate=44100 --globcmd=listen`
2. `C:\Portable\fmedia\fmedia.exe --globcmd=pause`
3. `C:\Portable\fmedia\fmedia.exe --globcmd=stop`

Crossing my fingers this is not impossible to fix ...

**Comment by stsaz** [comment]
It will be fixed in the next version.  Until then, just use `fmedia --globcmd=unpause` before `stop`.

**Comment by stsaz** [comment]
Finally, included the fix into v1.31
