### ISSUE TITLE
Information in terminal.

### ISSUE THREAD

**Issue by eskiq** [stsaz/fmedia#58]
I do have 1 file playing in terminal and I wanted to ask if I can somehow remove all information displayed in terminal like this:

```
fmedia v1.24 (win-x64)

#1 " - " 2.wav 0.34 MB, 0:02.005 (88,448 samples), 1411 kbps, WAVE, 44100 Hz, in
t16, stereo

[===================================.............................] 0:01 / 0:02
```

**Comment by stsaz** [comment]
Try `--notui` or suppress output entirely by using `fmedia ... >nil 2>nil`.

**Comment by eskiq** [comment]
I tried --notui, but its still displaying text output. This is my little bash script:

```
@echo off
goto Loop

:Loop
fmedia 3.wav
timeout /t 60 
goto Loop
```
How it should look like with "fmedia ... >nil 2>nil"?
