### ISSUE TITLE
StdOut broken in v1.25.2beta

### ISSUE THREAD

**Issue by 01yakiek** [stsaz/fmedia#62]
I'm here to report that the StdOut is completely broken where the buffer is no longer flushed properly. This causes StdIn chaos where it'll either end up looping on the unflushed buffer or generate gigabytes of wav file in mere 5 seconds.

Thank you.

**Comment by stsaz** [comment]
Nasty bug.  Thanks for reporting it!  Fixed in v1.25.3beta.
