### ISSUE TITLE
Can't deal with --start-dblevel parameter

### ISSUE THREAD

**Issue by cedschmidt-lab** [stsaz/fmedia#65]
Dear Stsaz, 

First of all, thanks for your work and I hope you are doing well with the current situation in UKRAINE... :-(

Here is an issue I'm facing trying to record from CLI in windows 1 with the command:
`fmedia --record -o test.m4a --format=int16 --channels=mono --rate=8000 --start-dblevel=-30 --stop-dblevel=-30;5000`

The process detect the initial threshold but get stuck just after.  Nothing happen and I have to ctrl+c to exit. The file is written with 0 kb. Here is what I get:

`fmedia v1.25.2 (win-x64)
Recording...  Source: float32 48000Hz mono.  Press "s" to stop.
0:02  [..........] -40dB / -40dB  19:27:47.234 :2910 [info] soundmod.startlevel: *1:    found -39.86dB peak at 0:02.266 (108,780 samples)`

Do you have any idea what is wrong or where it could come from?

Thanks for helping

Best regards,

**Comment by stsaz** [comment]
Oh, it seems that start/stop db level feature doesn't work at all on Windows.  But it's strange that it works fine on Linux.  Maybe it's WASAPI-related issue, I don't know yet.  I will investigate it, thank you very much for reporting!

> First of all, thanks for your work and I hope you are doing well with the current situation in UKRAINE... :-(

Yeah, well, thanks for the support!

**Comment by stsaz** [comment]
Fixed in v1.26.1.
If it still doesn't work for you, please reopen the issue.

PS

> --stop-dblevel=-30;5000

Note that you're using 5000 seconds interval here.

**Comment by cedschmidt-lab** [comment]
Hey, what a reactivity...

Just tried and it works like a charm... Yep, I thought the time parameter was in ms. 
Thanks a lot for the fit and for the app!!!

Best,
