### ISSUE TITLE
not able to record playback.

### ISSUE THREAD

**Issue by pilger** [stsaz/fmedia#66]
recording from playback isn't working in the latest release. i reverted back to version 1.24.1.

**Comment by stsaz** [comment]
It works fine for me with a simple command `fmedia --dev-loopback=1 --record -o 1.wav`.
Can you show what fmedia prints?  What doesn't work exactly?

**Comment by pilger** [comment]
i was in a hurry yesterday and hoped this would be something obvious. here are some more details. 

i'm using **_fmedia --record --dev-loopback=0 -o test.wav_** to record small snippets of audio from video playback in a chromium browser on windows 10. 

... and for some weird reason it is working today. :/ when i tried this yesterday fmedia printed several (four, iirc) "no such interface" errors and started writing to disk. the level meter showed no audio and the resulting wav file was of an expected size but corrupted and not playable. i checked if there are any (zombie) processes running that might access the audio interface and even restarted the system- but to no avail. it worked without a hitch after i reverted back to version 1.24.1.

i'm using scoop and installing from the standard 'extras' bucket. also i own an extern usb audio interface.

if this is happening again i'm going to report the error messages right away. sorry, for wasting your time.

**Comment by stsaz** [comment]
> "no such interface" errors

Looks like fmedia installation was broken somehow.  Did you unpack fmedia zip file into an existing fmedia installation directory or did you unpack into an empty directory?

But anyway, if the problem repeats in the future, please collect some debug info (with `-D` switch).  Maybe it's some kind of memory corruption bug and I won't be able to fix it without logs.
