### ISSUE TITLE
Issue with afilter.autoconv

### ISSUE THREAD

**Issue by Hindi** [stsaz/fmedia#69]
Hi,
I hope my question isn't silly, but I updated to the latest release version and I now have an error when I try to record using 

fmedia.exe --record --dev-loopback=0 -o "C:\Users\user\Documents\Videos\test" --globcmd=listen

11:41:01.939 :5bc8 [error] core: unknown output file format:
0:00  [..........] -40dB / -40dB  11:41:02.115 :5bc8 [error] track: *1: module afilter.autoconv, the last in chain, outputs more data

Is there a known fix for this problem?

**Comment by stsaz** [comment]
Hi!
You didn't specify output file extension:

> -o "C:\Users\user\Documents\Videos\test"

fmedia doesn't know what file format to use, therefore:

> unknown output file format

But anyway I'll try to fix the error message as it's not expected in this case. Thank you!

**Comment by Hindi** [comment]
Oh wow I feel so bad right now.
Thank you very much for clearing that up!
