### ISSUE TITLE
Record IAudioClient_Initialize 0x80070005 Access is denied

### ISSUE THREAD

**Issue by tomoyo255** [stsaz/fmedia#71]
Hello,

I regularly use fmedia (which I upgraded to latest 1.27.2 AMD64) to record audio over a Steinberg UR22C audio interface. Since recently, it doesn't work anymore. Recording now always leads to this error message:

```log
21:06:08.876 :29e4 [error] wasapi.in: *2:	open device #0: IAudioClient_Initialize: -2147024891 (0x80070005) Access is denied.   format:int16/44100/2
```

My Windows version:

```cmd
Microsoft Windows [Version 10.0.19043.1645]
```

Would you have any clue on what's happening?
If you need more information, please don't hesitate asking.

Thanks. Regards.

**Comment by stsaz** [comment]
Hello!

> Microsoft Windows [Version 10.0.19043.1645]

Seems like a recent update, April 2022.

First, try to search for answers with `IAudioClient_Initialize E_ACCESSDENIED`.  I found this:

> https://social.msdn.microsoft.com/Forums/en-US/2485e1e4-ac0a-4c79-af79-0e4b9e0d3588/iaudioclientinitialize-with-audclntsharemodeshared-fails-with-eaccessdenied

MS says the microphone can be disabled in Windows settings - is this the issue?

Next, try to fiddle with the Windows's audio settings for Recording Devices.

Next, try to force fmedia to use exclusive mode.  Set `exclusive_mode 2` in `fmedia.conf` here:

```
mod_conf "wasapi.in" {
...
	exclusive_mode 0
```

I won't be able to reproduce the problem myself, because I don't have the same Windows 10 version.  (On my Windows PC fmedia works fine.)

**Comment by tomoyo255** [comment]
> Hello!
> 
> > Microsoft Windows [Version 10.0.19043.1645]
> 
> Seems like a recent update, April 2022.
> (...)
> MS says the microphone can be disabled in Windows settings - is this the issue?
> (...)

Indeed, I didn't know about **Microphone Privacy Settings**. One of the latest updates must have either introduced it or reconfigure protection to disable access to the microphone to all apps.

The configuration has a big switch in the first place that says on/off at a global scale (**Allow apps to access your microphone**). It was off.

Then, the configuration allows to opt in/out apps of the Microsoft Store on an app basis on the one hand and, on the other hand, to opt in/out globally desktop apps (the usual exes) (**Allow desktop apps to access your microphone**). When grayed out it was obviously off, but when I enabled aforementioned big switch on, this was already implicitly on actually.

Thanks. Regards.

![MicrophonePrivacyBigSwitch](https://user-images.githubusercontent.com/43882812/166333464-b24799d6-2413-430a-9049-721a6afee422.png)
![MicrophonePrivacyDesktopAppSwitch](https://user-images.githubusercontent.com/43882812/166333205-8e862e7b-7f8f-4520-89d8-c9c8374c302a.png)
![MicrophonePrivacyFMedia](https://user-images.githubusercontent.com/43882812/166333214-47469f65-c79f-4eee-97d4-74cb30658bb3.png)

**Comment by stsaz** [comment]
Nice!  I'm gonna include it into Troubleshooting document.

**Comment by stsaz** [comment]
95cf945
