### ISSUE TITLE
Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [stsaz/fmedia#72]
@stsaz 

Could you please consider to improve source code to add multilanguage GUI using separate language file for each language?

Thanks.

**Comment by stsaz** [comment]
I've moved some strings to separate files:
https://github.com/stsaz/fmedia/blob/ccaaa006e879992b864c1b82a3e8a4d1d3779ba3/src/gui-winapi/gui_lang_en.txt
https://github.com/stsaz/fmedia/blob/ccaaa006e879992b864c1b82a3e8a4d1d3779ba3/src/gui-gtk/gui_lang_en.txt

All language codes should work automatically once added to `fmedia.gui` files.
This work is under another git branch `gui-lang`.  Hopefully the feature will be released with v1.28.

**Comment by bovirus** [comment]
@stsaz 

Please add italian language

[gui_lang_it.txt](https://github.com/stsaz/fmedia/files/8739120/gui_lang_it.txt)

**Comment by stsaz** [comment]
Wow, cool!
By the way, if you wish to be on the Contributors list here on fmedia's GitHub page, you should consider opening a Pull Request.  That way I can merge your patch, rather than committing by myself.

**Comment by bovirus** [comment]
@stzas

I consider to make a PR.
But I didn't find in repository the postion of file that instead I can get clicking on link.

Thanks.

**Comment by stsaz** [comment]
Nice! I've commented in your PR.
I understand that it's hard to make a perfect patch, so in general I can edit small things like file paths in patches from contributors, no problem.

**Comment by stsaz** [comment]
v1.28
