### ISSUE TITLE
linux: can't create pipe (probably ffos problem?)

### ISSUE THREAD

**Issue by Alexqwesa** [stsaz/fmedia#78]
trying to start fmedia with command:
```
 ./fmedia  --globcmd=start
18:59:03.723 :16d0 [error] globcmd: pipe connect: /tmp/.fmedia-unix-1000: (2) No such file or directory
```
it still can play audio files, but pipe file is not created

Also, i tried:
```
python3 -c "import socket as s; sock = s.socket(s.AF_UNIX, s.SOCK_STREAM | s.SOCK_NONBLOCK  ); sock.bind('/tmp/.record_linux-unix-1000')"
chmod a+rwx /tmp/.record_linux-unix-1000
```

but then it start with error:

```
20:41:22.730 :56eb [error] globcmd: pipe connect: /tmp/.record_linux-unix-1000: (111) Connection refused
```

**Comment by stsaz** [comment]
>  ./fmedia  --globcmd=start

`start` command only issues the command (to start playback) to an **existing** pipe, it doesn't create it.

You should first start the first fmedia instance with `--globcmd=listen`.
For example:
https://stsaz.github.io/fmedia/recording/#globcmd

**Comment by Alexqwesa** [comment]
`./fmedia  --globcmd=listen --globcmd.pipe-name=record_linux  `

This command works. Thanks)
