### ISSUE TITLE
Is the stop button far away? Exit button.

### ISSUE THREAD

**Issue by oklokl** [stsaz/fmedia#86]
`cmd`
`fmedia file1.mp3`

`fmedia file1.mp3 --background`

Music plays normally.
However
Pressing esc does not exit.

I'm curious about the user function buttons.
![2](https://user-images.githubusercontent.com/1571600/190953600-3f267693-46d8-4ed9-abbe-dea8b1152001.png)
I want to end the process of listening to music.
as a function button.

I know the pause button.

**Comment by stsaz** [comment]
Hello!

> fmedia file1.mp3

Press 's' key to stop playing, press 'q' to exit.  Press 'h' to see all available TUI commands and their assigned keys.  I know this isn't obvious for some people, but can you suggest something to improve user experience?  I guess I should at least add this information to README file...

> fmedia file1.mp3 --background

TUI commands won't work in this case.  You shouldn't normally use `--background` switch as this is an internal helper switch for `--globcmd`-related functions.

**Comment by oklokl** [comment]
Thank you very much. I like it because the process is simple. 
:)
