### ISSUE TITLE
fmedia-gui doesn't remember record settings

### ISSUE THREAD

**Issue by hced** [stsaz/fmedia#88]
When setting up things in the Record... dialog, I can record just fine during the current session, but when closing and reopening fmedia-gui.exe, those settings are gone. And I get the following error log when opening Record... and hitting Start/Stop:

`02:14:55.133 :2518 [error] wasapi.in: *4:	open device #0: unsupported format: int16/44100/2`

FYI, these are the settings I have to re-enter in Record... each program session:
```
Loopback Device:   0
Audio Format:      int16
Sample Rate (Hz):  44100
Channel:           2
```

I've tried both `false` and portable `fmedia.conf`, same result (non-persistent Record settings).

fmedia version: 1.29
OS: Windows 11 Pro (if Pro is still a thing) 21H2 (OS Build 22000.978)

**Comment by stsaz** [comment]
Hi, Henrik!  I agree this is somewhat annoying.  I haven't used Windows version for a while so it was never an issue for me...  Anyway, I'll add the functionality to save-restore recording settings in the next update.  Thanks for bringing this up!

**Comment by stsaz** [comment]
v1.29.1 now remembers all settings in Record dialog and restores them on next launch.  Please check it for your usecase, it should work.

**Comment by hced** [comment]
@stsaz You are one of my favorite developers of all time. Thanks for all your hard work on this fine app. The issue was 100% solved!
