### ISSUE TITLE
Overview description misleading

### ISSUE THREAD

**Issue by zohozer** [stsaz/fmedia#89]
This player it is intended for audio files, and the description from the Overview it is misleading, leaving the impression that you can play/record video files using this app.

Instead of: "fmedia is a fast media player/recorder/converter for Windows, macOS, Linux and FreeBSD. "

It should be: "fmedia is a fast audio media player/recorder/converter for Windows, macOS, Linux and FreeBSD. "

Best regards.

**Comment by stsaz** [comment]
Hi!  That's reasonable, thank you.  My initial plan was to also support video, but I still haven't found enough time to do that.
