### ISSUE TITLE
Won't run on RHEL 7.5 and won't compile

### ISSUE THREAD

**Issue by cfaber** [stsaz/fmedia#9]
Hi,
I'm trying to get this going on a RHEL 7.5 system I have and it won't run, It appears that you've dynamically compiled the binary releases (specifically the amd64 release) which is linking against a newer glibc. 

`vis@kenny:~/fmedia/fmedia-1$ ./fmedia test.flac --out test.mp3
fmedia v1.0 (linux-amd64)
15:41:34.113 [error] core: module /home/vis/fmedia/fmedia-1/mod/mpeg.so: library open: libmvec.so.1: cannot open shared object file: No such file or directory
15:41:34.113 [error] core: parse config: /nfs/hal/home/vis/fmedia/fmedia-1/fmedia.conf: 221:25: near "": "mod_conf": Success
`
libmvec arrived in glibc 2.2 and RHEL 7.5 runs with 2.1

**Comment by stsaz** [comment]
I think you'll need to build mpeg.so module yourself on your machine, please follow the steps described in README file ("build on linux" section).  You probably won't need to rebuild everything - just mpeg.so, and then overwrite my mpeg.so with yours.

**Comment by stsaz** [comment]
I've just looked at the module's dependencies: the problem is due to `libmp3lame-ff.so` dependency.  So you don't need to rebuild `mpeg.so`, but `libmp3lame-ff.so`.  Follow instructions `ff-3pt/README`, it should be quite easy to rebuild it.
