### ISSUE TITLE
Record system audio (windows output device?)

### ISSUE THREAD

**Issue by ItsCubeTime** [stsaz/fmedia#91]
Hi 👋I would like to be able to record audio created by software running on the system (namely Ardour in this case). Is this possible?

Under topbar > Record > Select Audio Device I only see input devices listed

**Comment by ItsCubeTime** [comment]
I was able to solve this by enabling "Stereo Mix" under windows settings
![image](https://user-images.githubusercontent.com/20190653/202928977-ad4392aa-3262-432e-a930-d18515ec0511.png)

![image](https://user-images.githubusercontent.com/20190653/202928950-1d30bc00-dbb6-434b-a93e-95275ee738ea.png)

**Comment by stsaz** [comment]
> Record > Select Audio Device

It shows only true input devices, such as microphones.  To record from a playback device you should use "Loopback Device Number" setting inside "Record -> Record..." dialog.  And keep in mind that you need to use Playback device number there (from `Playback -> Select Audio Device` dialog) - this is how this feature works on Windows.

But anyway, your solution is also fine!  This way Windows does the audio rerouting from playback to a recording device internally.
