### ISSUE TITLE
Fmedia does not play back short duration wave files

### ISSUE THREAD

**Issue by cheeryart2275** [stsaz/fmedia#97]
I work in pro audio and frequently have to preview a lot of short samples of audio. Like files less than 1 second long, drum hits and such. Fmedia opens these files but does not produce sound or the sound cuts off abruptly. Not just one specific file but all short wave files.

**Comment by stsaz** [comment]
What OS do you use?  Can you attach a sample file so I can reproduce this?

**Comment by cheeryart2275** [comment]
attached is an example WAV file with a bass drum sound that produces no sound on fmedia on my system. I'm on windows 10 enterprise, latest LTSC version, 64-bit.

--C.A.

**Comment by stsaz** [comment]
It seems that you didn't attach the file correctly - can you please do so via github's `Attach files` button?
Also, I've just tested the playback of some random 100ms wav file on win10, and it plays correctly for me.  I suspect that it's something inside your wav files that is not supported by fmedia (could it be that your wav files use compression or non-standard extensions?)

**Comment by cheeryart2275** [comment]
Thanks for trying to debug this. Here's a link:

https://f003.backblazeb2.com/file/amp-work/bassdrum.wav

I forgot to mention that I'm using the CLI version of fmedia. I'll see if I can make a screen capture to further display this problem. I'm pretty sure there's nothing special about my wave files since they come from many different sources and I've ran into this.

**Comment by stsaz** [comment]
Got it.  The problem is that there are currently several limitations in fmedia around 24-bit sample format.  I guess it's time to finally resolve this.

**Comment by cheeryart2275** [comment]
Ah, okay. Thanks for rooting out the problem! 24-bit is really common in audio and film audio production where you deal with very dynamic material where 16-bit is considered a bit "lofi". It'd be great if 24-bit support could be possible, love the quickness and snappiness of Fmedia and the versatility of the CLI player!

Cheers!

**Comment by stsaz** [comment]
> It'd be great if 24-bit support could be possible

Yes, 24-bit format support will be improved.  I'll update when the new version is released.

**Comment by stsaz** [comment]
@cheeryart2275  Hi!  24-bit format support is now included in phiola v2.0-beta9 (https://github.com/stsaz/phiola).  Please check if it works for you.
