### ISSUE TITLE
Help:I try to build this project in linux arm64 by using the build script.

### ISSUE THREAD

**Issue by moyang628** [stsaz/fmedia#98]
Hello,
  I try to build this project in ubuntu  20.04 arm64  to use the flutter plugin -record
  there is a lot of errors  such as when I compiling the MAC FLAC libs  and llibzstd-ff .
  Is this project  surportting the arm64 linux ?
  Thanks.

**Comment by stsaz** [comment]
Hello!
fmedia uses an ancient version of MAC lib, and it doesn't compile for arm64.  I build FLAC and zstd for android/arm64, and they work, so maybe there's just some minor issue with my makefiles - we can fix this. Here's what I suggest:

* Apply the patch from `apple-m1` branch to disable MAC and dynamic-audio-normalizer libs.
* Build; post all errors from FLAC and zstd (and maybe others) here.

P.S.
It would be even better if you can try to build phiola (https://github.com/stsaz/phiola), it's the next major update of fmedia.  It will be easier for me to fix issues there.  To disable MAC lib just apply the attached patch.
[phiola-alib3-disable-MAC.txt](https://github.com/stsaz/fmedia/files/13609075/phiola-alib3-disable-MAC.txt)

**Comment by moyang628** [comment]
Now I change to gcc to compile.
I skipped some lib ,and I made some changes to the build script and  the makefiles，
the libzstd-ff.so has been complied successfully.
but the next step stucked, here it comes:
==============================================
+cp -u ALAC/*.so \
	DynamicAudioNormalizer/*.so \
	fdk-aac/*.so \
	FLAC/*.so \
	mp3lame/*.so \
	mpg123/*.so \
	musepack/*.so \
	ogg/*.so \
	opus/*.so \
	vorbis/*.so \
	wavpack/*.so \
	_linux-arm64
+ cd ../../
+ echo Building zstd...
Building zstd...
+ cd ffpack/zstd
+ make -j8 -Rr
make -rR libzstd-ffpack.so
make[1]: Entering directory '/home/techo/fmedia-1.31/fmedia-src/ffpack/zstd'
make[1]: 'libzstd-ffpack.so' is up to date.
make[1]: Leaving directory '/home/techo/fmedia-1.31/fmedia-src/ffpack/zstd'
+ cd ..
+ test Linux == Linux
fmedia-autobuild.sh: 69: test: Linux: unexpected operator
+ make -j8 -Rr install
config.mk:1: ../../ffbase/conf.mk: No such file or directory
make: *** No rule to make target '../../ffbase/conf.mk'.  Stop.

================================

**Comment by stsaz** [comment]
The `autobuild` script is a little bit outdated, as it turns out.

In `Building zstd...` section replace `make -j8 -Rr install` with `make libzstd` - this will copy `fmedia-src/ffpack/zstd/libzstd-ffpack.so` to `fmedia-src/ffpack/_linux-arm64/` dir.  If not, you can copy it manually.
