### ISSUE TITLE
I like your software. fmedia is great!

### ISSUE THREAD

**Issue by 00000o1** [stsaz/fmedia#99]
I saw you are revising the command line options. I hope you don't get rid of `--dev-loopback` and `--out=@stdout` it's really useful!

**Comment by stsaz** [comment]
I'm glad you like it!

> I hope you don't get rid of --dev-loopback and `--out=@stdout` it's really useful!

Of course, they both are essential, I don't plan to drop them.
With phiola this looks like this:
`phiola rec -loopback -dev 1 -o @stdout.wav | your_program`

**Comment by 00000o1** [comment]
Thank you. I will look up philoa now
